apiVersion: v1
kind: Service
metadata:
  namespace: movie-system
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5000
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
